name: Build and Deploy

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '18'  # adjust Java version as needed

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Deploy JAR to GitHub Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          target/*.jar  # adjust the path to your JAR file
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        distribution: 'public'  # Provide the required input 'distribution'
